apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: httpd-ingress
spec:
  rules:
  - host: {{ .Values.domain }}
    http:
      paths:
      - path: /
        backend:
          serviceName: "httpd-service"
          servicePort: 80
